DZ-12 docker-2
Otus-DevOps-2022-02/daniilrostov_microservices pull request #2
Opened 2022-05-15 21:09 UTC by daniilrostov

Создан образ в Яндкс облаке при помощи docker-machine

2022-05-16 08:43 UTC, mrgreyves requested changes
Здравствуйте!)
Вам нужно немного исправить репозиторий
Нужно перенести тесты из предыдущего репозитория

2022-05-16 20:41 UTC, daniilrostov commented
Тест падает при старте контейнера. Похоже что проблема в коде. Его надо приложения. Его надо исправлять?

2022-05-17 08:59 UTC, mrgreyves requested changes
Здравствуйте!
Вам стоит дополнительно проверить Dockerfile
Кажется что в нем проблемы с mongodb
Ну и с установкой монги в целом так же могут быть проблемы

2022-05-17 08:59 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
Стоит проверить

2022-05-17 09:57 UTC, daniilrostov commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
Да. В докерфайле была проблема. Спасибо

2022-05-18 08:47 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)

2022-05-18 10:35 UTC, merged